export const componentGroup = { title: '展示组件', key: 'showdata' };

export const componentsList = [
  { path: '/pages-tmui/showData/avatar', title: '头像 avatar' },
  { path: '/pages-tmui/showData/qrcode', title: '二维码 qrcode' },
  { path: '/pages-tmui/showData/badge', title: '徽标 badge' },
  { path: '/pages-tmui/showData/card', title: '卡片 card' },
  { path: '/pages-tmui/showData/carousel', title: '轮播 carousel' },
  { path: '/pages-tmui/showData/collapse', title: '折叠面板 collapse' },
  { path: '/pages-tmui/showData/comment', title: '评论 comment' },
  { path: '/pages-tmui/showData/cell', title: '单元格 cell' },
  { path: '/pages-tmui/showData/countdown', title: '倒计时 countdown' },
  { path: '/pages-tmui/showData/descriptions', title: '描述 descriptions' },
  { path: '/pages-tmui/showData/image', title: '图片 image' },
  { path: '/pages-tmui/showData/indexes', title: '列表索引 indexes' },
  { path: '/pages-tmui/showData/more', title: '显示更多 more' },
  { path: '/pages-tmui/showData/result', title: '结果页 result' },
  { path: '/pages-tmui/showData/popover', title: '气泡卡片 popover' },
  { path: '/pages-tmui/showData/statistic', title: '数值显示 statistic' },
  { path: '/pages-tmui/showData/table', title: '表格 table' },
  { path: '/pages-tmui/showData/tabs', title: '选项卡 tabs' },
  { path: '/pages-tmui/showData/tag', title: '标签 tag' },
  { path: '/pages-tmui/showData/timeline', title: '时间轴 timeline' },
  { path: '/pages-tmui/showData/tree', title: '树 tree' },
  { path: '/pages-tmui/showData/virtual-list', title: '虚拟列表 virtual-list' },
  { path: '/pages-tmui/showData/waterfall', title: '瀑布流 waterfall' },
];
