export const componentGroup = { title: '展示组件', key: 'showdata' }

export const componentsList = [
  { path: '/pages-tmui/showdata/avatar', title: '头像 avatar' },
  { path: '/pages-tmui/showdata/qrcode', title: '二维码 qrcode' },
  { path: '/pages-tmui/showdata/badge', title: '徽标 badge' },
  { path: '/pages-tmui/showdata/card', title: '卡片 card' },
  { path: '/pages-tmui/showdata/carousel', title: '轮播 carousel' },
  { path: '/pages-tmui/showdata/collapse', title: '折叠面板 collapse' },
  { path: '/pages-tmui/showdata/comment', title: '评论 comment' },
  { path: '/pages-tmui/showdata/cell', title: '单元格 cell' },
  { path: '/pages-tmui/showdata/countdown', title: '倒计时 countdown' },
  { path: '/pages-tmui/showdata/descriptions', title: '描述 descriptions' },
  { path: '/pages-tmui/showdata/image', title: '图片 image' },
  { path: '/pages-tmui/showdata/indexes', title: '列表索引 indexes' },
  { path: '/pages-tmui/showdata/more', title: '显示更多 more' },
  { path: '/pages-tmui/showdata/result', title: '结果页 result' },
  { path: '/pages-tmui/showdata/popover', title: '气泡卡片 popover' },
  { path: '/pages-tmui/showdata/statistic', title: '数值显示 statistic' },
  { path: '/pages-tmui/showdata/table', title: '表格 table' },
  { path: '/pages-tmui/showdata/tabs', title: '选项卡 tabs' },
  { path: '/pages-tmui/showdata/tag', title: '标签 tag' },
  { path: '/pages-tmui/showdata/timeline', title: '时间轴 timeline' },
  { path: '/pages-tmui/showdata/tree', title: '树 tree' },
  { path: '/pages-tmui/showdata/virtual-list', title: '虚拟列表 virtual-list' },
  { path: '/pages-tmui/showdata/waterfall', title: '瀑布流 waterfall' },
]
